baseURL = "http://wiki.ryecscu.com"
languageCode = "en-ca"
title = "CSCU Wiki"
theme = "hugo-theme-learn"

[params]
	editUrl = "https://github.com/mohoromitch/csg/edit/master/content/"
	author = "et al"
	description = "Openly editable information repository by RUCS students, for RUCS students."
	showVisitedLinks = false
	disableSearch = false
	disableAssetsBusting = false
	disableInlineCopyToClipBoard = false
	disableShortcutsTitle = false
	disableLanguageSwitchingButton = true
	ordersectionsby = "weight"
	themeVariant = "blue"
[outputs]
	home = [ "HTML", "RSS", "JSON" ]
